#!/usr/bin/env bash
# Regenerate the plain-text refresh prompt from the markdown master.
# The two copies drifted before; deriving one from the other stops that recurring.
set -euo pipefail
cd "$(dirname "$0")"
{
  echo "DASHBOARD SCAN & REVIEW — ONE PROMPT"
  echo "Supabase project: hsmuxmvhgteexanssigc"
  echo
  echo "GENERATED from FULL-REFRESH-PROMPT.md — do not edit this file by hand."
  echo "Edit the .md, then run scripts/routine/build-prompt-txt.sh"
  echo
  sed -e 's/^> \{0,1\}//' \
      -e 's/\*\*//g' -e 's/`//g' \
      FULL-REFRESH-PROMPT.md
} > FULL-REFRESH-PROMPT.txt
echo "wrote FULL-REFRESH-PROMPT.txt ($(grep -c "" FULL-REFRESH-PROMPT.txt) lines)"
