-- Business Numbers: how each service is doing this month, against the SAME DAYS last month.
--
-- Applied live on 22 Sep 2026 as three objects — pull the current definitions with:
--   select pg_get_functiondef('public.biz_bucket'::regproc);
--   select pg_get_viewdef('public.web_business_numbers'::regclass, true);
--   select pg_get_viewdef('public.web_business_quotes'::regclass, true);
--
-- SAME DAYS, not same months. On the 22nd, a whole August against three weeks of
-- September says every service is collapsing — every month, until the 30th. A page that
-- cries wolf for three weeks in four stops being read.
--
-- Dated on CONFIRMATION, not booking month: "what have we won this month" and "what is
-- billed this month" are different questions, and a retainer booked forward answers them
-- differently. This asks the first.
--
-- biz_bucket() maps Service Department to the five the business is run by. LP and HUB are
-- one team; WEB-US (KS) is WEB-US with a sub-team tag. Anything unrecognised stays as
-- 'Other' rather than being dropped, so the parts still add to the whole.
--
-- The quotes view needs one more thing: all 101 hand-entered and email-found deals carry
-- a BLANK Service Department, so they all landed in Other and WEB-UK looked like it had
-- no pipeline at all. Department is not asked for when a deal is created and should not
-- start being asked for just to make a page add up — so it falls back to the department
-- that client's own revenue is booked under (by value), then to their GEO, then Other.
-- That moved 54 open quotes out of Other and put WEB-UK's $240k pipeline where it belongs.

-- ── Corrected 22 Sep 2026: revenue is dated on START DATE, not Confirmation Date ─────
-- The first version dated revenue on confirmation, which is defensible on its own terms
-- ("what did we win this month") but disagreed with the Business Overview sheet the team
-- actually reads. WEB-US was where it showed: $60,116 against the sheet's $31,445 for
-- 1–22 August, nearly double. The other four services barely moved either way — their
-- work usually starts in the month it is confirmed in, and WEB-US books further ahead,
-- so the two dates only pull apart there.
--
-- A second set of numbers nobody can reconcile is worse than no numbers. Verified after
-- the change: 1–22 Aug reads 19,335 / 24,015 / 49,660 / 31,444 / 950 against the sheet's
-- 19,335 / 24,014 / 49,662 / 31,445 / 950, and all of September totals $109,911 on both
-- sides. Rows with no start date fall in no month, exactly as the sheet treats them —
-- 6 revenue-bearing rows out of 3,221.
