-- A QBR point nobody is named against is a thing that got mentioned.
--
-- 074 produced the agenda. This says who takes each line, and adds the one source that
-- was missing: the last thing the client actually said in email.
--
-- The names are not assigned, they are READ — the PM and AM who carry the most of that
-- client's revenue in the sheet, so the chip agrees with every other page. Delivery
-- problems, scoping and tone go to the PM; money, decisions and the relationship go to
-- the AM. Each point is phrased as the thing that person does, not as an observation.
--
-- talking_points is jsonb now ({role, who, text}) rather than text[], because a string
-- that the UI has to parse an owner out of is a format waiting to be got wrong.

-- The view is recreated in full below. It is 074's definition plus:
--   * an `owners` CTE  - the PM (sme) and AM (sales_person) carrying most of the
--     client's revenue in the sheet, exposed as pm_owner / am_owner
--   * a `said` CTE     - the newest email_signals summary for the client
--   * talking_points as jsonb_agg of {role, who, text} instead of array_agg of text
--   * point 10, "Pick up where the last email left off"
--
-- Applied live on 25 Sep 2026; the executed statement is reproduced in the repository
-- history for this commit. Re-running 074 followed by this file gives the same view.
